# -*- coding: utf-8 -*-
"""student

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dy-G2lTjD6D3ZH1By8bG_jZYG5GmG4nz
"""

pip install faker

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set()

np.random.seed(42)

n = 250

data = {
    "Student_ID": range(1, n+1),
    "Name": [f"Student_{i}" for i in range(1, n+1)],
    "Gender": np.random.choice(["Male", "Female"], n),
    "Department": np.random.choice(["CSE", "IT", "ECE"], n),
    "Year": np.random.choice(["1st", "2nd", "3rd"], n),
    "Maths": np.random.randint(35, 100, n),
    "Science": np.random.randint(35, 100, n),
    "English": np.random.randint(35, 100, n),
    "Attendance": np.random.randint(50, 101, n),
    "Internal_Marks": np.random.randint(0, 26, n)
}

df = pd.DataFrame(data)

df.head()

df["Total"] = df["Maths"] + df["Science"] + df["English"]
df["Average"] = df["Total"] / 3

def grade(avg):
    if avg >= 90:
        return "A+"
    elif avg >= 75:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 50:
        return "C"
    else:
        return "Fail"

df["Grade"] = df["Average"].apply(grade)

df.head()

print(df.describe())

top_students = df.sort_values(by="Total", ascending=False).head(5)
print("Top Performers:\n", top_students)

fail_students = df[df["Grade"] == "Fail"]
print("\nFailed Students:\n", fail_students)

dept_perf = df.groupby("Department")["Average"].mean()
print(dept_perf)

gender_perf = df.groupby("Gender")["Average"].mean()
print(gender_perf)


year_perf = df.groupby("Year")["Average"].mean()
print(year_perf)

dept_perf.plot(kind="bar", title="Department-wise Average Marks")
plt.show()

df["Department"].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.title("Department Distribution")
plt.ylabel("")
plt.show()

plt.hist(df["Average"])
plt.title("Distribution of Average Marks")
plt.xlabel("Average Marks")
plt.ylabel("Frequency")
plt.show()

plt.scatter(df["Attendance"], df["Average"])
plt.title("Attendance vs Average Marks")
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.show()

print("Average Marks:", df["Average"].mean())
print("Highest Marks:", df["Total"].max())
print("Lowest Marks:", df["Total"].min())